[program:crm-reverb]
command=php /var/www/crm-omnichannel/artisan reverb:start --host=127.0.0.1 --port=8080
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/crm-omnichannel/storage/logs/reverb.log
stopwaitsecs=60
